name: Dependency Update Check

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Check for updates
      run: |
        npx npm-check-updates -u --target minor
        npm install
        npm audit fix
    
    - name: Run tests
      run: |
        npm run lint
        npm run test
      continue-on-error: true
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates for:
          - Minor and patch version updates
          - Security vulnerability fixes
          
          Please review the changes and ensure all tests pass before merging.
          
          ### Checklist
          - [ ] All tests pass
          - [ ] No breaking changes introduced
          - [ ] Application builds successfully
          - [ ] Manual testing completed (if needed)
        branch: automated-dependency-updates
        delete-branch: true